Added setup endpoint coverage
dev-yoonik/YK-BiT-SDK-Python pull request #4
Opened 2021-11-22 19:17 UTC by jppdpf

2021-11-22 21:25 UTC, dev-yoonik commented on sample/run_bit_sample.py
> +   - Restart the BiT App
This restart and repeat logic are not needed.

2021-11-22 22:02 UTC, vitormcpedro requested changes

2021-11-22 22:02 UTC, vitormcpedro commented on yk_bit/bit.py
> +    return True
This function never returns False. If we are raising an exception when an error occurs, we do not need to return a value.

2021-11-23 12:19 UTC, mlourencoeb commented on yk_bit/bit.py
> +    return True
Setup logic with true/false seems to ugly. if the setup does not work, just let the exception being raised.

2021-12-02 16:16 UTC, dev-yoonik approved these changes

2021-12-02 16:30 UTC, vitormcpedro requested changes

2021-12-02 16:30 UTC, vitormcpedro commented on sample/run_bit_sample.py
> +        bit_setup = setup()
setup() method is not returning a value right now

2021-12-02 16:30 UTC, vitormcpedro commented on sample/run_bit_sample.py
> +        exit()
why exiting here?

2021-12-04 00:23 UTC, vitormcpedro approved these changes

2021-12-04 00:24 UTC, merged